// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./mammoth-browser.d.ts" />
import mammoth from "mammoth/mammoth.browser";
import JSZip from "jszip";
import { parseDocument } from "htmlparser2";
import type { AnyNode, Element } from "domhandler";
import { XMLParser } from "fast-xml-parser";
import { createFile, safeLink, type JsonNode, type DocFile } from "./index";
import { type OfficeImport, parseXml } from "./office";

type Mark = NonNullable<JsonNode["marks"]>[number];
const normalize = (s: string) => s.replace(/[\s\u200b\ufeff]+/gu, "");
export function documentText(n: JsonNode): string {
  return (n.text ?? "") + (n.content ?? []).map(documentText).join("");
}
export function htmlToDocument(html: string): JsonNode {
  const root = parseDocument(html, { decodeEntities: true });
  function inline(nodes: AnyNode[], marks: Mark[] = []): JsonNode[] {
    const out: JsonNode[] = [];
    for (const n of nodes) {
      if (n.type === "text") {
        if (n.data)
          out.push({
            type: "text",
            text: n.data,
            ...(marks.length ? { marks } : {}),
          });
        continue;
      }
      if (n.type !== "tag") continue;
      const e = n as Element,
        tag = e.name.toLowerCase();
      if (
        [
          "script",
          "style",
          "iframe",
          "object",
          "embed",
          "audio",
          "video",
        ].includes(tag)
      )
        continue;
      if (tag === "br") {
        out.push({ type: "hardBreak" });
        continue;
      }
      if (tag === "img") {
        if (
          /^data:image\/(png|jpeg|gif|webp);base64,/i.test(e.attribs.src ?? "")
        )
          out.push({
            type: "image",
            attrs: { src: e.attribs.src, alt: e.attribs.alt ?? "" },
          });
        else if (e.attribs.alt)
          out.push({ type: "text", text: `[${e.attribs.alt}]` });
        continue;
      }
      if (tag === "input" && e.attribs.type === "checkbox") {
        const checked =
          e.attribs.checked === "checked" ||
          e.attribs.checked === "" ||
          e.attribs.checked === "true";
        out.push({
          type: "text",
          text: checked ? "☒" : "☐",
          ...(marks.length ? { marks } : {}),
        });
        continue;
      }
      // Footnote marker labels are generated by Mammoth and aren't source text.
      const markType = (
        {
          strong: "bold",
          b: "bold",
          em: "italic",
          i: "italic",
          u: "underline",
          s: "strike",
          del: "strike",
          sup: "superscript",
          sub: "subscript",
          code: "code",
        } as Record<string, string>
      )[tag];
      const next = [...marks];
      if (markType && !next.some((m) => m.type === markType))
        next.push({ type: markType });
      if (tag === "a" && safeLink(e.attribs.href ?? ""))
        next.push({
          type: "link",
          attrs: { href: e.attribs.href, target: null },
        });
      out.push(...inline(e.children, next));
    }
    return out;
  }
  function attrs(e: Element) {
    const a: Record<string, unknown> = {};
    if (e.attribs.id) a.id = e.attribs.id.slice(0, 250);
    if (["rtl", "ltr"].includes(e.attribs.dir)) a.dir = e.attribs.dir;
    return a;
  }
  function paragraph(
    content: JsonNode[],
    attributes: Record<string, unknown> = {},
  ): JsonNode[] {
    const result: JsonNode[] = [];
    let current: JsonNode[] = [];
    for (const n of content) {
      if (n.type === "image") {
        if (current.length)
          result.push({
            type: "paragraph",
            attrs: attributes,
            content: current,
          });
        current = [];
        result.push(n);
      } else current.push(n);
    }
    if (current.length || !result.length)
      result.push({ type: "paragraph", attrs: attributes, content: current });
  const BLOCK_TAGS = new Set([
    "p", "h1", "h2", "h3", "h4", "h5", "h6",
    "ul", "ol", "li", "table", "tbody", "thead", "tfoot", "tr", "td", "th",
    "blockquote", "pre", "hr",
  ]);
  const hasBlockElement = (children: AnyNode[]): boolean =>
    children.some((child) => {
      if (child.type !== "tag") return false;
      const el = child as Element;
      const name = el.name.toLowerCase();
      return (
        BLOCK_TAGS.has(name) ||
        (el.children ? hasBlockElement(el.children) : false)
      );
    });
  const containerBlocks = (children: AnyNode[]): JsonNode[] => {
    if (!hasBlockElement(children)) {
      const inlines = inline(children);
      return inlines.length ? paragraph(inlines) : [{ type: "paragraph" }];
    }
    const b = blocks(children);
    return b.length ? b : [{ type: "paragraph" }];
  };
  function blocks(nodes: AnyNode[]): JsonNode[] {
    const out: JsonNode[] = [];
    for (const n of nodes) {
      if (n.type === "text") {
        if (n.data.trim()) out.push(...paragraph(inline([n])));
        continue;
      }
      if (n.type !== "tag") continue;
      const e = n as Element,
        t = e.name.toLowerCase();
      if (["script", "style", "iframe", "object", "embed"].includes(t))
        continue;
      if (t === "p") {
        out.push(...paragraph(inline(e.children), attrs(e)));
      } else if (/^h[1-6]$/.test(t)) {
        out.push({
          type: "heading",
          attrs: { ...attrs(e), level: +t[1] },
          content: inline(e.children).filter((n) => n.type !== "image"),
        });
      } else if (t === "ul" || t === "ol") {
        const children = e.children.filter(
          (n) => n.type === "tag" && (n as Element).name === "li",
        ) as Element[];
        out.push({
          type: t === "ol" ? "orderedList" : "bulletList",
          attrs: t === "ol" ? { start: Number(e.attribs.start) || 1 } : {},
          content: children.map((li) => {
            const b = containerBlocks(li.children);
            return {
              type: "listItem",
              content: b[0].type === "paragraph" ? b : [{ type: "paragraph" }, ...b],
            };
          }),
        });
      } else if (t === "table") {
        const rows: Element[] = [];
        function findRows(es: AnyNode[]) {
          for (const c of es) {
            if (c.type !== "tag") continue;
            const child = c as Element;
            if (child.name === "tr") rows.push(child);
            else if (["tbody", "thead", "tfoot"].includes(child.name))
              findRows(child.children);
          }
        }
        findRows(e.children);
        const content = rows
          .map((row) => ({
            type: "tableRow",
            content: row.children
              .filter(
                (c) =>
                  c.type === "tag" &&
                  ["td", "th"].includes((c as Element).name),
              )
              .map((c) => {
                const cell = c as Element;
                const body = containerBlocks(cell.children);
                return {
                  type: cell.name === "th" ? "tableHeader" : "tableCell",
                  attrs: {
                    colspan: Math.max(
                      1,
                      Math.min(1000, Number(cell.attribs.colspan) || 1),
                    ),
                    rowspan: Math.max(
                      1,
                      Math.min(1000, Number(cell.attribs.rowspan) || 1),
                    ),
                    colwidth: null,
                  },
                  content: body.length ? body : [{ type: "paragraph" }],
                };
              }),
          }))
          .filter((row) => row.content.length);
        if (content.length) out.push({ type: "table", content });
      } else if (t === "blockquote")
        out.push({ type: "blockquote", content: blocks(e.children) });
      else if (t === "pre")
        out.push({
          type: "codeBlock",
          content: inline(e.children).map((n) => ({ ...n, marks: [] })),
        });
      else if (t === "hr") out.push({ type: "horizontalRule" });
      else if (t === "img") out.push(...paragraph(inline([e])));
      else out.push(...blocks(e.children));
    }
    return out;
  }
  const content = blocks(root.children);
  return {
    type: "doc",
    content: content.length ? content : [{ type: "paragraph" }],
  };
}
const orderedParser = new XMLParser({
  preserveOrder: true,
  ignoreAttributes: false,
  trimValues: false,
  parseTagValue: false,
  processEntities: true,
});
export function wordParagraphs(xml: string): string[] {
  let tree: any[];
  try {
    tree = orderedParser.parse(xml) as any[];
  } catch {
    const texts = [
      ...xml.matchAll(/<(?:\w+:)?t\b[^>]*>([\s\S]*?)<\/(?:\w+:)?t>/g),
    ];
    return texts.map((m) =>
      String(
        new XMLParser({ parseTagValue: false, trimValues: false }).parse(
          `<text>${m[1]}</text>`,
        ).text ?? "",
      ),
    );
  }
  const result: string[] = [];
  function text(nodes: any[]): string {
    let s = "";
    for (const n of nodes)
      for (const [k, v] of Object.entries(n)) {
        if (k === ":@" || k.endsWith(":del") || k.endsWith(":instrText"))
          continue;
        if (k.endsWith(":t") || k === "t")
          s += (v as any[]).map((n) => n["#text"] ?? "").join("");
        else if (k.endsWith(":tab")) s += "\t";
        else if (k.endsWith(":br")) s += "\n";
        else if (k.endsWith(":checkBox") || k === "checkBox") {
          let checked = false;
          if (Array.isArray(v)) {
            for (const child of v) {
              const attrs = child[":@"] ?? {};
              const val = attrs["@_w:val"] ?? attrs["@_val"];
              for (const childKey of Object.keys(child)) {
                if (childKey === ":@") continue;
                if (childKey.endsWith(":checked") || childKey === "checked") {
                  if (val === undefined || val === "1" || val === "true" || val === "on")
                    checked = true;
                } else if (childKey.endsWith(":default") || childKey === "default") {
                  if (val === "1" || val === "true" || val === "on")
                    checked = true;
                }
              }
            }
          }
          s += checked ? "☒" : "☐";
        } else if (Array.isArray(v)) s += text(v);
      }
    return s;
  }
  function walk(nodes: any[]) {
    for (const n of nodes)
      for (const [k, v] of Object.entries(n)) {
        if (k === ":@" || k.endsWith(":del")) continue;
        if (k.endsWith(":p") || k === "p") {
          const t = text(v as any[]);
          if (t) result.push(t);
        } else if (Array.isArray(v)) walk(v);
      }
  }
  walk(tree);
  return result;
}
export async function importDocx(
  bytes: Uint8Array,
  title: string,
  inspected: { zip: JSZip; part: string; xml: string },
): Promise<OfficeImport> {
  const { zip, xml } = inspected,
    warnings: string[] = [],
    features: string[] = [];
  let html = "";
  let fallback = 0;
  const source = wordParagraphs(xml);
  if (xml.includes("purl.oclc.org/ooxml")) {
    features.push("strict-ooxml");
    for (const f of Object.values(zip.files))
      if (!f.dir && /\.xml$|\.rels$/.test(f.name)) {
        const value = await f.async("string");
        if (value.includes("http://purl.oclc.org/ooxml/"))
          zip.file(
            f.name,
            value
              .replaceAll(
                "http://purl.oclc.org/ooxml/wordprocessingml/main",
                "http://schemas.openxmlformats.org/wordprocessingml/2006/main",
              )
              .replaceAll(
                "http://purl.oclc.org/ooxml/officeDocument/relationships",
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
              )
              .replaceAll(
                "http://purl.oclc.org/ooxml/drawingml/main",
                "http://schemas.openxmlformats.org/drawingml/2006/main",
              ),
          );
      }
    warnings.push("Strict OOXML namespaces were normalized for conversion.");
  }
  try {
    const input = features.includes("strict-ooxml")
      ? await zip.generateAsync({ type: "uint8array" })
      : bytes;
    const result = await mammoth.convertToHtml(
      { arrayBuffer: input.slice().buffer },
      {
        includeEmbeddedStyleMap: false,
        externalFileAccess: false,
        ignoreEmptyParagraphs: false,
        styleMap: ["u => u"],
        convertImage: mammoth.images.imgElement(async (image) => {
          if (
            !["image/png", "image/jpeg", "image/gif", "image/webp"].includes(
              image.contentType,
            )
          ) {
            warnings.push(
              `An ${image.contentType || "unknown"} image was replaced by an editable label.`,
            );
            return { src: "", alt: `Unsupported ${image.contentType} image` };
          }
          return {
            src: `data:${image.contentType};base64,${await image.readAsBase64String()}`,
          };
        }),
      },
    );
    html = result.value;
    warnings.push(...result.messages.map((m) => m.message));
  } catch (e) {
    fallback = 1;
    warnings.push(
      `Semantic conversion needed a text recovery: ${e instanceof Error ? e.message : String(e)}`,
    );
  }
  let content: JsonNode;
  try {
    content = html
      ? htmlToDocument(html)
      : ({
          type: "doc",
          content: source.map((t) => ({
            type: "paragraph",
            content: [{ type: "text", text: t }],
          })),
        } as JsonNode);
  } catch {
    fallback = 1;
    warnings.push("Deeply nested layout was flattened to editable paragraphs.");
    content = {
      type: "doc",
      content: source.map((text) => ({
        type: "paragraph",
        content: [{ type: "text", text }],
      })),
    };
  }
  if (!content.content?.length)
    content = { type: "doc", content: [{ type: "paragraph" }] };
  let output = normalize(documentText(content));
  const missing = source.filter((t) => !output.includes(normalize(t)));
  if (missing.length) {
    warnings.push(
      `${missing.length} source paragraphs were retained in an additional recovered-text section.`,
    );
    content.content!.push(
      {
        type: "heading",
        attrs: { level: 2 },
        content: [{ type: "text", text: "Recovered document text" }],
      },
      ...missing.map((text) => ({
        type: "paragraph",
        content: [{ type: "text", text }],
      })),
    );
    output = normalize(documentText(content));
  }
  let supplementary = 0;
  for (const path of Object.keys(zip.files).filter((p) =>
    /word\/(header\d*|footer\d*)\.xml$/i.test(p),
  )) {
    const value = await zip.file(path)!.async("string");
    if (!value.trim()) continue;
    try {
      parseXml(value, path);
    } catch {
      warnings.push(`An unreadable header/footer (${path}) was omitted.`);
      continue;
    }
    const ps = wordParagraphs(value);
    if (ps.length) {
      supplementary += ps.length;
      content.content!.push(
        {
          type: "heading",
          attrs: { level: 2 },
          content: [
            {
              type: "text",
              text: path.includes("header")
                ? "Imported header"
                : "Imported footer",
            },
          ],
        },
        ...ps.map((text) => ({
          type: "paragraph",
          content: [{ type: "text", text }],
        })),
      );
    }
  }
  if (supplementary)
    warnings.push(
      "Header/footer text is retained as document sections rather than repeated page furniture.",
    );
  const checks: Record<string, RegExp> = {
    tables: /<w:tbl\b/,
    images: /<w:(drawing|pict)\b/,
    footnotes: /<w:footnoteReference\b/,
    endnotes: /<w:endnoteReference\b/,
    tracked_changes: /<w:(ins|del)\b/,
    math_equations: /<m:oMath\b/,
    text_boxes: /<w:txbxContent\b/,
    content_controls: /<w:sdt\b/,
    embedded_objects: /<w:object\b/,
    rtl: /<w:(bidi|rtl)\b/,
  };
  for (const [name, re] of Object.entries(checks))
    if (re.test(xml)) features.push(name);
  if (features.includes("tracked_changes"))
    warnings.push(
      "Tracked changes are imported as accepted text; review history is not retained.",
    );
  if (features.includes("math_equations"))
    warnings.push(
      "Equations are retained as recovered text when available; editable equation layout is not supported.",
    );
  if (features.includes("embedded_objects"))
    warnings.push(
      "Embedded OLE objects are not executed or embedded into the document editor.",
    );
  warnings.push(
    "Continuous layout preserves semantic content; exact Word pagination, floating placement and font styling may differ.",
  );
  const file = createFile("doc", title) as DocFile;
  file.content = content;
  const stats: Record<string, number> = {
    sourceParagraphs: source.length,
    sourceCharacters: source.join("").length,
    importedCharacters: documentText(content).length,
    recoveredParagraphs: missing.length,
    supplementaryParagraphs: supplementary,
    fallback,
  };
  let images = 0,
    tables = 0;
  function count(n: JsonNode) {
    if (n.type === "image") images++;
    if (n.type === "table") tables++;
    n.content?.forEach(count);
  }
  count(content);
  stats.images = images;
  stats.tables = tables;
  return {
    file,
    report: {
      format: "docx",
      warnings: [...new Set(warnings)].slice(0, 100),
      features,
      stats,
      textPreserved: source.every((t) => output.includes(normalize(t))),
    },
  };
}
